version: "3"
services:
  api_service:
    build: ./hotel-api
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: hoteldb
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net:
