version: "3"
services:
  react_client:
    build: ./hotel-client
    ports:
      - 80:80
    networks:
      - springapimysql-net
    depends_on:
      - api_service

  api_service:
    build: ./hotel-api
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: hoteldb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_MAX_ALLOWED_PACKET: 64M
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
networks:
  springapimysql-net:
